_meta:
    doc: ENC[AES256_GCM,data:yG4peefE13N1JJkE1Q6GyZEiDv2V87pFN8nih/hMvhfxljifUn5eIegOkKZC7u1p1FBs5YXX8ktbCg3thGbCsjcx6UhSl9RvjJTlDLoiJ65CsY2ImwZEajz/7BTOHnFa5k2a940A9aVHtK+8LZB7wHvBPXKv4kpmDiqUGvEFRO7nOYmMr+b0RNFULhcs27CSgKHYr30PPRF78+A1+mS97xg4tv76U2DgXAif3teu0g==,iv:KSSzjwuKLi030PJITcAWHcpuJYh4M197fngvotO/5b8=,tag:NvqKorvwNvQcLd24Y8wrxw==,type:str]
    owner: ENC[AES256_GCM,data:anSQpAm7614=,iv:7jPMO9y6AYMMsQpfitLkwV7YBqNdxQzOSmJcRaoBwPU=,tag:XYuTfwBsGk5nAFoNd5QBMQ==,type:str]
    phase: ENC[AES256_GCM,data:fw==,iv:lE9mK9dbOPiO+S+ByVoc24WROy41I3xaedWCzgj5GzI=,tag:nTJj7wwhwpIL/xN75yPu5g==,type:str]
    reconciled_with: ENC[AES256_GCM,data:NGG7K6lUPRYD/MnezrX+jPHTcJecHf9Z2DvOrAO4KHP1x9r4NPZd51Fig4gmrKKhPv9xyzRdrZrvM16ydjAlchNZF7vfzW5SHIjvd4VzrJwJ5Iyt77c5C0ENg1MkuGaRCsjvVw8IWIHoNyWMQ+eYcqzH3FQ0RQ==,iv:eDkNmmfaryNd0X8/M2RD5BHLjgRSRiNUDpnq3fr5YfY=,tag:2Avb0+BOm8cw7MPVlhlsNw==,type:str]
odoo:
    ODOO_ADMIN_PASSWD: ENC[AES256_GCM,data:MT5FetlzF98=,iv:nMNeDw8EKdrfrvcIvwiMV6m2DtvuTqD6Cgot0EB2pfo=,tag:howpsmVn0oqSTbayCgM5Hg==,type:str]
    ODOO_DB_PASSWORD: ENC[AES256_GCM,data:J2QgbPp70Go=,iv:Xb3wFSM9luvuA99zeaOdlYqyZDcdAV+x5ThtVeCVvuk=,tag:XTD7LbsGLpOvCadl4Zj2hA==,type:str]
postgres:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:EDDjGxtML9s=,iv:sxeIXG3Y51M0AnD0h1ybqMszz9X8uazReQU3EgVUTy4=,tag:RkdD5r05YTXWplNlzmLfQw==,type:str]
    WAREHOUSE_READER_PASSWORD: ENC[AES256_GCM,data:5pw5XI0VYsQ=,iv:JtCk+UoYJpWOHP5E1S0LYXdQ9zvhrQZA1Kmq3Ag91bU=,tag:imCEHuvqvYB6IgF6pWZPjA==,type:str]
    POSTGRES_EXPORTER_PASSWORD: ENC[AES256_GCM,data:1/wQZ0RxCF0=,iv:Hwa1nAzoMVFbzbEUlOm30/aZqPmHhKsJmCb34xEExfk=,tag:lLAQ1OHwgC6IJL1O/zu2XA==,type:str]
redis:
    REDIS_PASSWORD: ENC[AES256_GCM,data:qhOhGhRCsZ8=,iv:FGb8mf7MRUMqlFkawxTXuXZfKcjOZsAtVj3k786gfsg=,tag:GaSxU85N6y2oAg0slURvHg==,type:str]
observability:
    GRAFANA_ADMIN_PASSWORD: ENC[AES256_GCM,data:+4a9WB57D/Q=,iv:B7swRx+tzqJyAWJCa8H26fhnJbFNbizDotV4NOEKACg=,tag:9cKFFNj4xkcR0yp0jINuZA==,type:str]
warehouse:
    WAREHOUSE_DB_PASSWORD: ENC[AES256_GCM,data:o0+QjFsnmA8=,iv:4IuYTtSBmZrXdnwsra3nDocLKraARRUbgSBgkrcCm6E=,tag:3ztYpN74rE8Kw9eqXskgDQ==,type:str]
warehouse_masking:
    _contract: ENC[AES256_GCM,data:eH/QE0Vy4odM3LlIR72gnqK9QeZ0+aG9YDD+KToHNZB6zpwQwOUY2QDefBFPcl3l3WEeVGfQv3SulTLKrv7tNCYQrNn4VLSZkfUt91FOONOT6cWv4eT4v77SBEfX6fm/2tyJi2iY9ojwIjC2Rkqc0v3mnDRTwV631XYnM6J9mfw/acYks4gctEN5q4wAbNl8vvxlUo7bzb4K00UnpucjsTiLgsaPcRIxUPgz/YmR/w==,iv:5TMlcRJA3wKSQptNMa5DbPUk+kUkR6tn8igwbwM439o=,tag:buH8sU/iVCzCIQexeGvYPw==,type:str]
    WAREHOUSE_MASK_SALT_DEFAULT: ENC[AES256_GCM,data:4lC5VUKyuc8=,iv:Y83a4D/ZxF2Z9k5P034fWgkAeM9haPNd4PxI5CYzn2Y=,tag:zF+U/17bbOWxTi2q0sIX5g==,type:str]
    WAREHOUSE_MASK_SALT_BCT: ENC[AES256_GCM,data:S7AuAMnYQ5s=,iv:tDnqgF8qv4dsU/1cS6rOjJNEz46W7oUau1MLLIeWivY=,tag:pE140cBDMNTYrqIXPnu7nw==,type:str]
login_gateway:
    _contract: ENC[AES256_GCM,data:FRMJ51grnboNW8nYa4Zn8QXusu50RRi4bDeUqu7XvCZFMvPUBl3E90U8KON0ALz4c3t1DgYHvx/DskDQr0awv2Zn0TRXAM6dwu1SFcbMYc0a7puqtbw+h0rbW12Pqy8Xjh7t+VHriHNEjQdV6/gesryqxhDrYq+ueNiYxkfGk4pNUFWP48vcRI4Xz749kVI+c78xYhtCmra1C8L0dpP4SXgfASL+uBV/QzFz07aOsvWvmpK0izBzePBQ09/9tATEGYrIXM+vDmur0b6vUkQTmALw4ENi59IZUiI7kdWVlc4huBcnCCKKyI9iubmMvJOF7C4zpFCagX6QhHRvRx2i6+keqW0=,iv:arMiVPyP+nLyHv76UKpNdXckwOnb7+Egn7QPienelbc=,tag:7WdtyXrueVRA0BnKK7ajHQ==,type:str]
    LOGIN_GATEWAY_JWT_KID: ENC[AES256_GCM,data:Uz178y2u+3E=,iv:l5EWQ4nkNl+Ee25QArE+Xml/GhsKcQGvWRgyaOLNP/8=,tag:zalO2/KlPQzmqnpJOJLhYQ==,type:str]
    LOGIN_GATEWAY_REFRESH_COOKIE_SECRET: ENC[AES256_GCM,data:y4qKOMXlDUA=,iv:9Un/z2cIr6wroArrvv4uBn/XI7zrv/a6DcXZykf3nec=,tag:MRgeX2iO3OOGv2TV9yCUIA==,type:str]
    LOGIN_GATEWAY_JWT_PRIVATE_KEY_PATH: ENC[AES256_GCM,data:hOYgRtvEbI98suj5dbX73azeakTnndQJeWe5gg==,iv:RScqy8ptOrpjaNMLYQQ/l77DAFS4ZvJjZ9JamZlpaow=,tag:VNljeDDJ2xZbpGdCbeV6sw==,type:str]
    LOGIN_GATEWAY_JWT_PUBLIC_KEY_PATH: ENC[AES256_GCM,data:cR21NwRWtkemRDVyjQz8A4sIoh9Wgr/t6pTQ,iv:lsuaWfUmfLKuDdSHLU+jXknVTCBJt3BDlJUaQsQMuMA=,tag:nCvTlts+bW+lzRhahynUqA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqYkpBclJ2YUxxK09TcUh0
            c0QxRTFTWEZvZlZWa3NwK05IbjhQR1U2S3dzCm81SktyN0pTei80VDZDSGg0WW5z
            Ymd4a1BSa2N0MUxoNURSeXVqMWhRR3MKLS0tIFF0UkhEL2J2ekRXSjArRm5SQUxD
            bUJJcXdUNmhLK1UwTTBDZG1kM2ZyczAKF64DjuWvXzD3z7twCBI6vd3XsgEE8Z9/
            D4Aa/IPQ1rcokEqmhqoGy9AmO3SW1BpMWQyKmdNmP+NNH6BzkSpAtw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14mh5ttdkqd9sah0pnpdx3mx385pdsy7ukjh663th8zw3hmyh2pzsytq7ws
    lastmodified: "2026-08-30T21:03:51Z"
    mac: ENC[AES256_GCM,data:Ek+PtEL26C+2nnzjLOsPEJlGwzT82GRM5gg2RKbbTLwUs5+YiiJJTub8PfbkuU2tkxTeuBW4cBu6GXGImu3WB+HUyhcvmImOw95wvxNsMWutRuCo24f6Otf7J5L1MhyyorfMfCGDTS/W7WLIDOqoPbSFFMV7180JJb6NaleewLc=,iv:DOCGJ0nQLmLwHRVrTSkNOQTRlsFpPwqAmeIz3NyEzKo=,tag:TH5BNcccmxuxZ0No1m/+lA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.0
