_meta:
    doc: ENC[AES256_GCM,data:fuWJmBlW0AoGcekBQ9x6IIlchyVorJ7z7Cz4uyA3oQVOXekbSfufVnemv+p3zSygg5X4llTG+osMNB1GYNL4OeX+g2KEWX8QmvpM3itBVHieB/eXdYPoslut5rOnvb64CPkhtJW+VT/m9RKEmK6hoWE0VbcY0wwUjKmdA7PJT9gllRhNcIYzHrxP4tdkPQNpURS8LoWh1OsMJF4FVOiwkISRMFRmx9YT4OkgLOt6PQ==,iv:siH21UaZuyByq3uIqCesT8TX+m+brxsTtyEUdrZ7YoY=,tag:MSJSm5lagEVTy6ZthAIBgQ==,type:str]
    owner: ENC[AES256_GCM,data:Wi2VCdYoA4g=,iv:Cmi2nkhQbQlOtJqMZJHSdiPdfNfP4bcBALMr95s7dbw=,tag:zgO1xy56lx7SJMiLYrIFgA==,type:str]
    phase: ENC[AES256_GCM,data:mw==,iv:ckywGHALSb3lmPLjqtH4tiQ4K5dT7mznpVnDxDnsCLY=,tag:yWG6jKnWf5SqsrcPFUL3yA==,type:str]
    reconcile_with: ENC[AES256_GCM,data:SfRKOHRcMHz3sG0l,iv:qtHfYZNqDzL9DN06V4j/onznZEII+6HpPqqmlEa30rI=,tag:QWRdov8jBAWMgxrePAOeCg==,type:str]
odoo:
    ODOO_ADMIN_PASSWD: ENC[AES256_GCM,data:fJHYPzquGEc=,iv:HBSCAUPstieqd4rxZ69s1RxsIa3TBUXjkqjyADqGh+s=,tag:qtRAjz7FV9vpEOfdKpOfxw==,type:str]
    ODOO_DB_PASSWORD: ENC[AES256_GCM,data:C6XpPiiYRgU=,iv:Mh8PrASZ8FsWCDmdXH76qjwz/+wRrVu/TZCKHYEgHzQ=,tag:Quh4KyhCDstLWgX2FahYQQ==,type:str]
postgres:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:+dnj8EhDYqg=,iv:cImv2+KjsLLwEKwLJHHooKzE6LBi9PSmwM8a91wQz20=,tag:0uhzq+KdOTYGxixlLBTqdQ==,type:str]
    WAREHOUSE_READER_PASSWORD: ENC[AES256_GCM,data:acqKFWz+z2k=,iv:9a12nzZDrNYWV82EYYI1h+Eh856lQcaJ5kVOq3cKW6E=,tag:hGDUsQS3XGdXixE0nBj2gA==,type:str]
    POSTGRES_EXPORTER_PASSWORD: ENC[AES256_GCM,data:EMCnbg9cTSI=,iv:xINOf+/ImZmsRprQzJYVrii+j4645jEbo6bZbATVR4U=,tag:lO1nZ/WhBto5GHGohnivbw==,type:str]
redis:
    REDIS_PASSWORD: ENC[AES256_GCM,data:2Vo6HoezFWY=,iv:LR+9Sgar4kCc5kd59D4qQg4KvjBMyTJclyWr/a5BuHI=,tag:odpc0HttuY3lLTdrzLumWg==,type:str]
observability:
    GRAFANA_ADMIN_PASSWORD: ENC[AES256_GCM,data:gyFwdYhL5mc=,iv:6vF6f1n19pUJ/QDTQvXOStnH0eoy24MBKvRZIN+PR3A=,tag:Ih/A1IGHPSRjG6XrohppKA==,type:str]
warehouse_masking:
    _contract: ENC[AES256_GCM,data:Fx+xYK3zi4gREqjcUd8IQBqhvidCZHc3gZTo+npzOIQk8snB+hMEjMWEsZhLp/eoaYvwMHV4QcdePXikUGAUVRXCjI1KVWDHZPcjM897ixIJ+P4Rj9X6bF888h0W2IxTLwweR0ut0FF4XhptiQZ/Y39Vl9uLSEiVhe8NWKYWzocg5CyFqnA=,iv:Z1ghsCYXyjvnLk2zt2aun5tTrL1eRpL0Rk1yuIHAhTs=,tag:G8lzj9Lh6/RiIgJYQjwZvg==,type:str]
    WAREHOUSE_MASK_SALT_DEFAULT: ENC[AES256_GCM,data:NLzzVk71KNg=,iv:BkLgoKFdAit7MMaybNENxmR+Wi01SxVf5B3StixWgeE=,tag:kmUntHVIgSGWrXz53K0qzg==,type:str]
    WAREHOUSE_MASK_SALT_ACME: ENC[AES256_GCM,data:6/TMjl4ei58=,iv:p/ikQeZgO0ftfwUQSu62FbXFMHVl/UhZQ9rRNRaHhCE=,tag:TYER1GccoVQwWwshCKRx8Q==,type:str]
login_gateway:
    _contract: ENC[AES256_GCM,data:APw98utpkFckNL4QJZRa+jpzq7Fu8PjoReIE9puOzx14quzm7iwZSW7yJY2fjvZAon61RFqV8Xf8cfWmbj65wzYySiqQpt8kszFatTT3a089GIbXAPpDKLjYfedxUmesa0NaJ6GQxHsOATSx5IAZhlizDuufblf45v/5S1BwSMR66s1fXz5J,iv:6acMARn/j/AP9QsHBF/JiNSDdzXXHVNM1GmUqfGJnoM=,tag:yAR5EW/Dfr6IOYlVVAVU/A==,type:str]
    LOGIN_GATEWAY_JWT_PRIVATE_KEY_PATH: ENC[AES256_GCM,data:NA2uJkRC6USRGnSlAEjkz9Ww5q/7h/GLxRZ2e4TARI24U6o+,iv:QKZouV62eAdElmpERQefwjp59mMmN/my6OlgvqYGzLc=,tag:6tNgebeSj8acYHfPb1/9cw==,type:str]
    LOGIN_GATEWAY_JWT_PUBLIC_KEY_PATH: ENC[AES256_GCM,data:75A8AiLRkNcvCUTa4Gl4IZPhL1Ri3T7g4VSXhI0EVAREXlKs,iv:3Cu/bp15K6xCRjZvlJUvKFFBOHgcHf/ZMZBd8yU+dHs=,tag:EAI3x2CUnOr6/4gntEoKFQ==,type:str]
    LOGIN_GATEWAY_JWT_ISSUER: ENC[AES256_GCM,data:e3Ht/5Kbvl6ot/J0F8ZfAg1Wciyk0Jr3LaupOQ==,iv:6HI9VB4xhiGL2HtasdOHZvKUxeBjfnjVHFLLH+7a4b0=,tag:WmlUdkmonhwGe8T27GKwPQ==,type:str]
    LOGIN_GATEWAY_JWT_AUDIENCE: ENC[AES256_GCM,data:mGKt6K8ctyvhQVftkPU=,iv:xiPiGjitVn/wUh4ip6Om8HtkyZFFxh5IB7D4/nuyzuE=,tag:ASuUtMH09yLPuIdpS0GWuA==,type:str]
    LOGIN_GATEWAY_JWKS_URL: ENC[AES256_GCM,data:diMOjz5USByHMhlTmzQuf25NQx6aKB2oxEX4pAVQwJG2bntCkmV1PmEZu8ceeAc3,iv:tSb49D9TrBS5LZpMCQ2MTXIqJ27iWK2ezR982fR4R9o=,tag:JNmLqaSvC0htrEuo9L2uCQ==,type:str]
    LOGIN_GATEWAY_REFRESH_COOKIE_SECRET: ENC[AES256_GCM,data:obbZrsWaPHQ=,iv:17l0Mtc8csj4rVP8dM1Drdgj4S9iRyB4+xj/7KxT6xE=,tag:TVLTageAo7V1h7dcp2ReVg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxMHluZWpIdFJuWlZSRklU
            NkhkYlBlZkRaZERxZjZZOE9EZUV6UjFyNXlFCnhxM2IxdjJqeGlYWkx2M0hvM1hY
            KzNyeGJqQWhCeGM0MHJnTjF3N0FxU0kKLS0tIGNkczJtNWYrbVVDeGJlYyt4NnNx
            a2JBZ3ljd3RzSjF3OHN2dlZJTmVaVEEKgmV6fGx3fZgURVTRgJUR018XPFZcHwz6
            PP991kQquxgOMnXOyYrL0iu6y/VtEsD/9P1CnTfjsoIVAgLd6GG98g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14mh5ttdkqd9sah0pnpdx3mx385pdsy7ukjh663th8zw3hmyh2pzsytq7ws
    lastmodified: "2026-08-30T20:23:04Z"
    mac: ENC[AES256_GCM,data:uTsl1vuUuvvO+Txu8W1sRFYRSl//UKndFJfSjyvwkqDcNM0/UM+4ZUINn4nU+aF0PKLRrr53XSBtHW/basN78e9uMyKBjZfnYVf7NrjkrIWr6iuGF9zQSX1oYv7wCrCVm1XR9uDbKN+1DxJJ3N06iCKzq8ZKVyqFv3gq4pT2qPc=,iv:+OmZ18pz3+nePl3jO14wr3AIHkaQGK5crxOSjNfi+No=,tag:ifWn0LiExtXx+n4n6XJIWQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.0
